[package]
name = "fluxemu-math"
version = "0.0.1"
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
nalgebra = { workspace = true }
num = { workspace = true }
rangemap = { workspace = true }
serde = { workspace = true }
