[package]
name = "fluxemu-graphics"
version = "0.0.1"
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
bytemuck = { workspace = true }
fluxemu-math = { workspace = true }
nalgebra = { workspace = true }
palette = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
wgpu = { workspace = true, optional = true }

[features]
webgpu = ["dep:wgpu"]
