[package]
name = "fluxemu-definition-mos6502"
version = "0.0.1"
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[[bench]]
harness = false
name = "bench"

[dependencies]
fluxemu-runtime = { workspace = true }
heapless = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
bytes = { workspace = true }
criterion = { workspace = true }
fluxemu-math = { workspace = true }
