[package]
name = "fluxemu-system"
version = "0.0.1"
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
fluxemu-program = { workspace = true }
fluxemu-runtime = { workspace = true }
serde = { workspace = true }
