[package]
name = "fluxemu-system-nintendo-gameboy"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
fluxemu-definition-intel8080 = { workspace = true }
fluxemu-program = { workspace = true }
fluxemu-runtime = { workspace = true }
fluxemu-system = { workspace = true }
wgpu = { workspace = true, optional = true }

[features]
webgpu = ["dep:wgpu"]
