[package]
name = "fluxemu-system-nintendo-gameboy"
version = "0.0.1"
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
fluxemu-definition-intel8080 = { workspace = true }
fluxemu-program = { workspace = true }
fluxemu-runtime = { workspace = true }
fluxemu-system = { workspace = true }
wgpu = { workspace = true, optional = true }

[features]
webgpu = ["dep:wgpu"]
