[package]
name = "fluxemu-shell-nuttallite"
version = "0.1.0"
edition = "2024"
description = "A multi system emulator"
license = "GPL-3.0-or-later"

[package.metadata.nuttx]
priority = 100
stack-size = 16384
config = "shell/nuttallite/nuttx/config"
board-config-directory = "shell/nuttallite/nuttx/board"

[package.metadata.nuttx.boards.raspberrypi-pico-2]
target = "thumbv8m.main-nuttx-eabihf"
target-cpu = "cortex-m33"
opt-level = "s"
firmware-file = "nuttx.uf2"

[package.metadata.nuttx.boards.raspberrypi-pico]
target = "thumbv6m-nuttx-eabi"
target-cpu = "cortex-m0plus"
opt-level = "z"
firmware-file = "nuttx.uf2"

[lib]
crate-type = ["staticlib"]

[dependencies]
egui = { workspace = true }
fluxemu-audio = { workspace = true }
fluxemu-egui-software-renderer = { workspace = true }
fluxemu-environment = { workspace = true }
fluxemu-frontend = { workspace = true }
fluxemu-graphics = { workspace = true }
fluxemu-input = { workspace = true }
fluxemu-program = { workspace = true }
fluxemu-runtime = { workspace = true }
libc = { workspace = true }
nalgebra = { workspace = true }
palette = { workspace = true }
redb = { workspace = true }
ringbuffer = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

# Machines
fluxemu-system-atari-2600 = {
  workspace = true,
}
fluxemu-system-nintendo-nes = {
  workspace = true,
}
fluxemu-system-other-chip8 = {
  workspace = true,
}

[build-dependencies]
bindgen = "0.72"
