[package]
name = "fluxemu-shell-destinezite"
version = "0.1.0"
edition = "2024"
description = "Desktop port of the FluxEMU emulation framework"
license = "GPL-3.0-or-later"

[package.metadata.deb]
maintainer = "Kay <lambdadeltakay@proton.me>"
license-file = ["../../LICENSE", "0"]
assets = [
  ["target/release/fluxemu-shell-destinezite", "usr/bin/", "755"],
  [
    "assets/linux/launch.desktop",
    "usr/share/applications/fluxemu-shell-destinezite-launch.desktop",
    "644"
  ],
  [
    "assets/linux/run.desktop",
    "usr/share/applications/fluxemu-shell-destinezite-run.desktop",
    "644"
  ],
  [
    "assets/linux/mime.xml",
    "usr/share/mime/packages/fluxemu-shell-destinezite.xml",
    "644"
  ],
]
section = "games"
priority = "optional"
depends = "$auto"
maintainer-scripts = "assets/linux/debian"

[dependencies]
bytemuck = { workspace = true }
clap = { workspace = true }
cpal = "0.18"
egui = { workspace = true }
fluxemu-audio = { workspace = true }
fluxemu-egui-software-renderer = { workspace = true }
fluxemu-environment = { workspace = true }
fluxemu-frontend = { workspace = true }
fluxemu-graphics = { workspace = true }
fluxemu-input = { workspace = true }
fluxemu-program = { workspace = true, features = ["mmap"] }
fluxemu-runtime = { workspace = true }
gilrs = "0.11"
nalgebra = { workspace = true }
palette = { workspace = true }
pollster = { workspace = true }
redb = { workspace = true }
strum = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

# Webgpu required stuff
egui-wgpu = { version = "0.36", optional = true }
wgpu = { workspace = true, optional = true }

# Windowing required stuff
egui-winit = { version = "0.36", optional = true }
softbuffer = { version = "0.4", optional = true }
winit = { version = "0.30", optional = true }

# DRM required stuff
drm = { version = "0.15", optional = true }
evdev = { version = "0.13", optional = true }
input = { version = "0.10", features = ["log"], optional = true }
libseat = { version = "0.2", optional = true }
nix = { version = "0.31", features = ["event", "poll"], optional = true }
udev = { version = "0.9", optional = true }
xkbcommon = { version = "0.9", optional = true }

# Machines
fluxemu-system-atari-2600 = { workspace = true, optional = true }
fluxemu-system-atari-lynx = { workspace = true, optional = true }
fluxemu-system-nintendo-gameboy = { workspace = true, optional = true }
fluxemu-system-nintendo-nes = { workspace = true, optional = true }
fluxemu-system-other-chip8 = { workspace = true, optional = true }

[features]
default = ["webgpu", "windowing"]
drm = [
  "dep:drm",
  "dep:evdev",
  "dep:input",
  "dep:libseat",
  "dep:nix",
  "dep:udev",
  "dep:xkbcommon",
  "wgpu/drm"
]
webgpu = [
  "dep:egui-wgpu",
  "dep:wgpu",
  "fluxemu-graphics/webgpu",
  "fluxemu-system-atari-2600/webgpu",
  "fluxemu-system-atari-lynx/webgpu",
  "fluxemu-system-nintendo-gameboy/webgpu",
  "fluxemu-system-nintendo-nes/webgpu",
  "fluxemu-system-other-chip8/webgpu",
]
windowing = [
  "dep:egui-winit",
  "dep:softbuffer",
  "dep:winit",
  "fluxemu-frontend/external-file-dialog"
]
