[package]
name = "fluxemu-frontend"
version = "0.0.1"
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
fluxemu-audio = { workspace = true }
fluxemu-graphics = { workspace = true }
fluxemu-input = { workspace = true }
fluxemu-math = { workspace = true }
fluxemu-program = { workspace = true }
fluxemu-runtime = { workspace = true }
fluxemu-system = { workspace = true }
nalgebra = { workspace = true }
palette = { workspace = true }
rand = { workspace = true }
ringbuffer = { workspace = true }
ron = { workspace = true }
rust-i18n = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
