[package]
name = "fluxemu-frontend"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
byte-unit = { workspace = true }
egui = { workspace = true, features = ["rayon"] }
egui_extras = { workspace = true }
egui-toast = { workspace = true }
fluxemu-audio = { workspace = true }
fluxemu-environment = { workspace = true }
fluxemu-graphics = { workspace = true }
fluxemu-input = { workspace = true }
fluxemu-math = { workspace = true }
fluxemu-program = { workspace = true }
fluxemu-runtime = { workspace = true }
fluxemu-system = { workspace = true }
indexmap = { workspace = true }
nalgebra = { workspace = true }
palette = { workspace = true }
pollster = { workspace = true }
rand = { workspace = true }
rfd = { workspace = true, optional = true }
ringbuffer = { workspace = true }
ron = { workspace = true }
rust-i18n = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
sysinfo = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[features]
external-file-dialog = ["dep:rfd"]
