name: "package"
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  debian-trixie-x86_64:
    name: Debian Trixie (x86_64-unknown-linux-gnu)
    runs-on: ubuntu-latest
    container: debian:trixie
    steps:
      - name: Install Linux dependencies
        run: |
          apt update
          apt install -y --no-install-recommends \
            rustup \
            ca-certificates \
            curl \
            git \
            build-essential \
            pkg-config \
            libasound2-dev \
            libudev-dev \
            libvulkan-dev \
            libgl-dev \
            libx11-dev \
            libxkbcommon-dev \
            libwayland-dev \
            libinput-dev \
            libseat-dev \
            libbz2-dev

      - uses: actions/checkout@v7
        with:
          submodules: "true"

      - name: Install cargo-deb
        run: cargo install cargo-deb --locked

      - name: Build Debian package
        run: cargo deb -p fluxemu-shell-destinezite --features drm --target x86_64-unknown-linux-gnu

      - name: Upload Debian package
        uses: actions/upload-artifact@v7
        with:
          name: fluxemu-shell-destinezite-x86_64-unknown-linux-gnu-deb
          path: target/debian/fluxemu-shell-destinezite_*_amd64.deb
          if-no-files-found: error
